TEMP_LATEX = 'temp/expression.png'
USERS_PATH = 'data/users.json'
MAX_WIDTH, MAX_HEIGHT = 1280, 1280
MAX_EXPRESSION_LENGTH = 300
MAX_EXPRESSION_ATOMS = 30
MAX_SAVE_ATOMS = 100
MAX_DIFF_ARGUMENTS_LENGTH = 10
